#ifndef _GENERRORS_H_
#define _GENERRORS_H_

// Instruction Processing Return Codes
#define GARBAGE		1
#define SYM_ERR		2
#define ALLOC_ERR	3
#define FAULT		4

struct program;

// Compiler Errors generated by the compiler itself
void print_memory_error(struct program *prog);
void print_fault(const char *reason, struct program *prog);

#endif

